Repository boostcampwm2023/web04-ALGOCEAN, pull requests merged in 2023-11, with the labels that each got.

#42 pull request 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE/기본-풀리퀘.md
Labels: docs

#43 backend 개발환경 설정
  BE/.eslintrc.js
  BE/.gitignore
  BE/.pnp.cjs
  BE/.pnp.loader.mjs
  BE/.prettierrc
  BE/.yarn/releases/yarn-4.0.1.cjs
  BE/.yarnrc.yml
  BE/README.md
  BE/nest-cli.json
  BE/package.json
  BE/src/app.controller.spec.ts
  BE/src/app.controller.ts
  BE/src/app.module.ts
  BE/src/app.service.ts
  BE/src/main.ts
  BE/test/app.e2e-spec.ts
  BE/test/jest-e2e.json
  BE/tsconfig.build.json
  BE/tsconfig.json
  BE/yarn.lock
Labels: BE

#40 mock data 제작 및 prettier 설정 파일 이동
  FE/.prettierrc
  FE/src/assets/questionlistMockdata.json
Labels: docs

#46 prisma 설정
  BE/.gitignore
  BE/.pnp.cjs
  BE/.pnp.loader.mjs
  BE/.yarnrc.yml
  BE/package.json
  BE/prisma/schema.prisma
  BE/tsconfig.json
  BE/yarn.lock
Labels: new feature, BE

#48 readme에 개발 위키 링크 추가
  README.md
Labels: docs, 🐢slow

#47 답변 등록 API, 채택 API
  BE/package.json
  BE/src/answers/answers.controller.spec.ts
  BE/src/answers/answers.controller.ts
  BE/src/answers/answers.module.ts
  BE/src/answers/answers.service.spec.ts
  BE/src/answers/answers.service.ts
  BE/src/answers/dto/adopt-answer.dto.ts
  BE/src/answers/dto/create-answer.dto.ts
  BE/src/answers/dto/update-answer.dto.ts
  BE/src/app.module.ts
  BE/src/main.ts
  BE/src/prisma.service.ts
  BE/yarn.lock
Labels: new feature, BE

#51 단일 질문 보기 API
  BE/src/questions/dto/read-question.dto.ts
  BE/src/questions/questions.controller.spec.ts
  BE/src/questions/questions.controller.ts
  BE/src/questions/questions.module.ts
  BE/src/questions/questions.service.spec.ts
  BE/src/questions/questions.service.ts
Labels: new feature, BE

#60 단일 질문 생성 API
  BE/src/questions/dto/create-question.dto.ts
  BE/src/questions/questions.controller.ts
  BE/src/questions/questions.service.ts
Labels: new feature, BE

#57 페이지네이션 컴포넌트 구현 및 질문 리스트 컴포넌트에 적용
  FE/src/App.tsx
  FE/src/components/MainHeader/MainHeader.styles.ts
  FE/src/components/MainHeader/MainHeader.tsx
  FE/src/components/MainNav/MainNav.styles.ts
  FE/src/components/MainNav/MainNav.tsx
  FE/src/components/Pagination/Pagination.styles.ts
  FE/src/components/Pagination/Pagination.tsx
  FE/src/components/QuestionList/QuestionList.styles.ts
  FE/src/components/QuestionList/QuestionList.tsx
  FE/src/components/index.ts
  FE/style/common.css
  FE/style/index.css
Labels: new feature, FE

#85 개발편의성을 위해 일시적으로 CORS 허용
  BE/src/main.ts
Labels: enhancement, BE

#84 CI/CD 설정
  BE/dockerfile
  README.md
Labels: enhancement, FE, BE

#61 단일 질문 삭제 API
  BE/src/questions/questions.controller.ts
  BE/src/questions/questions.service.ts
Labels: new feature, BE

#86 단일 질문 수정 API
  BE/src/questions/dto/update-question.dto.ts
  BE/src/questions/questions.controller.ts
  BE/src/questions/questions.service.ts
Labels: new feature, BE

#88 질문 검색 API
  BE/src/questions/questions.controller.ts
  BE/src/questions/questions.service.ts
Labels: new feature, BE

#91 질문 리스트, 필터, 정렬 API 통합
  BE/src/questions/dto/read-question-list-options.dto.ts
  BE/src/questions/questions.controller.spec.ts
  BE/src/questions/questions.controller.ts
  BE/src/questions/questions.service.spec.ts
  BE/src/questions/questions.service.ts
Labels: new feature, BE

#94 14 문서 에디터 적용
  FE/index.html
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/assets/uniqueQuestions.json
  FE/src/components/DocumentEditor/DocumentEditor.styles.ts
  FE/src/components/DocumentEditor/DocumentEditor.tsx
  FE/src/components/UniqueQuestions/UniqueQuestions.tsx
  FE/src/components/index.ts
  FE/src/main.tsx
  FE/src/pages/MainPage/MainPage.styles.ts
  FE/src/pages/MainPage/MainPage.tsx
  FE/src/pages/index.ts
  FE/src/styles/common.css
  FE/src/styles/index.css
  FE/src/styles/reset.css
  FE/src/styles/styled.d.ts
  FE/src/styles/theme.ts
  FE/src/types/type.d.ts
  FE/style/index.css
  FE/tsconfig.json
Labels: review, new feature, FE

#93 34 질문 리스트 api 연동
  FE/.gitignore
  FE/package-lock.json
  FE/package.json
  FE/src/api/index.ts
  FE/src/assets/questionlistMockdata.json
  FE/src/components/QuestionList/QuestionList.tsx
Labels: new feature, FE

#96 메인페이지 - 질문리스트 - 채택받은 질문 디자인 적용
  FE/package-lock.json
  FE/package.json
  FE/src/assets/icons/check-circle.svg
  FE/src/components/QuestionList/QuestionList.styles.ts
  FE/src/components/QuestionList/QuestionList.tsx
  FE/src/hooks/index.ts
  FE/src/vite-env.d.ts
  FE/svg.d.ts
  FE/tsconfig.json
  FE/vite.config.js
Labels: new feature, FE

#98 프론트엔드 build 에러 해결
  FE/package-lock.json
  FE/src/App.tsx
  FE/src/components/Pagination/Pagination.tsx
  FE/src/components/QuestionList/QuestionList.styles.ts
  FE/src/components/QuestionList/QuestionList.tsx
  FE/src/components/UniqueQuestions/UniqueQuestions.styles.ts
  FE/src/components/UniqueQuestions/UniqueQuestions.tsx
  FE/src/main.tsx
  FE/src/pages/MainPage/MainPage.tsx
  FE/src/pages/index.ts
  FE/vite.config.js
Labels: review, bug, FE

#95 작성 중인 글 서버에 주기적으로 저장 API
  BE/prisma/schema.prisma
  BE/src/questions/dto/update-question-draft.dto.ts
  BE/src/questions/questions.controller.spec.ts
  BE/src/questions/questions.controller.ts
  BE/src/questions/questions.service.spec.ts
  BE/src/questions/questions.service.ts
Labels: new feature, BE

#100 소셜 계정 로그인 API
  BE/package.json
  BE/prisma/schema.prisma
  BE/src/app.module.ts
  BE/src/auth/DTO/jwt-payload.dto.ts
  BE/src/auth/DTO/login.dto.ts
  BE/src/auth/auth.controller.spec.ts
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/auth.service.spec.ts
  BE/src/auth/auth.service.ts
  BE/src/auth/strategies/github.strategy.ts
  BE/src/auth/strategies/jwt.strategy.ts
  BE/src/users/users.module.ts
  BE/yarn.lock
Labels: BE

#101 이메일 로그인 API
  BE/src/auth/DTO/login.dto.ts
  BE/src/auth/auth.controller.ts
  BE/src/auth/auth.service.ts
Labels: BE

#107 4 질문 등록 페이지 레이아웃
  FE/.gitignore
  FE/src/App.tsx
  FE/src/components/DocumentEditor/DocumentEditor.styles.ts
  FE/src/components/DocumentEditor/DocumentEditor.tsx
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.style.ts
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.tsx
  FE/src/pages/index.ts
  FE/src/styles/index.css
  FE/src/styles/styled.d.ts
  FE/src/styles/theme.ts
Labels: review, new feature, FE

#104 질문 리스트 랜더링 로직 변경 & 메인페이지 관련 컴포넌트 CSS 변경
  FE/public/images/clock.png
  FE/public/images/fire.png
  FE/public/images/link.png
  FE/public/images/logo.png
  FE/src/components/MainHeader/MainHeader.styles.ts
  FE/src/components/MainHeader/MainHeader.tsx
  FE/src/components/MainNav/MainNav.styles.ts
  FE/src/components/Pagination/Pagination.styles.ts
  FE/src/components/QuestionList/QuestionList.styles.ts
  FE/src/components/QuestionProfile/QuestionProfile.styles.ts
  FE/src/components/QuestionProfile/QuestionProfile.tsx
  FE/src/components/UniqueQuestions/UniqueQuestions.styles.ts
  FE/src/components/UniqueQuestions/UniqueQuestions.tsx
  FE/src/pages/MainPage/MainPage.styles.ts
  FE/src/pages/MainPage/MainPage.tsx
  FE/src/styles/index.css
  FE/src/styles/reset.css
  FE/src/styles/styled.d.ts
  FE/src/styles/theme.ts
Labels: FE, refactor

#111 질문 리스트 레이아웃 GET API 수정
  FE/src/api/index.ts
  FE/src/components/QuestionList/QuestionList.tsx
Labels: bug, FE

#114 ENV로드 방식 변경
  BE/src/auth/strategies/github.strategy.ts
Labels: bug

#116 브라우저 Meta 정보 추가
  FE/index.html
  FE/public/favicon.ico
  FE/src/App.tsx
  FE/src/components/MainNav/MainNav.tsx
Labels: new feature, FE

#113 2023-11-23 HOTFIX 배포
  BE/src/auth/strategies/github.strategy.ts
  BE/src/auth/strategies/jwt.strategy.ts
  FE/.gitignore
  FE/index.html
  FE/public/favicon.ico
  FE/public/images/clock.png
  FE/public/images/fire.png
  FE/public/images/link.png
  FE/public/images/logo.png
  FE/src/App.tsx
  FE/src/api/index.ts
  FE/src/components/DocumentEditor/DocumentEditor.styles.ts
  FE/src/components/DocumentEditor/DocumentEditor.tsx
  FE/src/components/MainHeader/MainHeader.styles.ts
  FE/src/components/MainHeader/MainHeader.tsx
  FE/src/components/MainNav/MainNav.styles.ts
  FE/src/components/MainNav/MainNav.tsx
  FE/src/components/Pagination/Pagination.styles.ts
  FE/src/components/QuestionList/QuestionList.styles.ts
  FE/src/components/QuestionList/QuestionList.tsx
  FE/src/components/QuestionProfile/QuestionProfile.styles.ts
  FE/src/components/QuestionProfile/QuestionProfile.tsx
  FE/src/components/UniqueQuestions/UniqueQuestions.styles.ts
  FE/src/components/UniqueQuestions/UniqueQuestions.tsx
  FE/src/pages/MainPage/MainPage.styles.ts
  FE/src/pages/MainPage/MainPage.tsx
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.style.ts
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.tsx
  FE/src/pages/index.ts
  FE/src/styles/index.css
  FE/src/styles/reset.css
  FE/src/styles/styled.d.ts
  FE/src/styles/theme.ts
Labels: release

#103 랜덤 질문 API
  BE/src/questions/questions.controller.ts
  BE/src/questions/questions.service.ts
Labels: new feature, BE

#105 게시글 생성 및 게시글 조회 API 수정
  BE/src/questions/dto/create-question.dto.ts
  BE/src/questions/questions.service.ts
Labels: BE, refactor

#141 등급 API
  BE/src/users/users.controller.ts
  BE/src/users/users.service.ts
Labels: new feature, BE

#140 누적 포인트 API
  BE/src/users/users.controller.ts
  BE/src/users/users.service.ts
Labels: new feature, BE

#147 질문 API soft delete 적용
  BE/src/questions/questions.service.ts
Labels: BE

#143 좋아요 API
  BE/src/likes/create-likes.dto.ts
  BE/src/likes/likes.controller.spec.ts
  BE/src/likes/likes.controller.ts
  BE/src/likes/likes.module.ts
  BE/src/likes/likes.service.spec.ts
  BE/src/likes/likes.service.ts
Labels: new feature, BE

#144 swagger 설정
  BE/package.json
  BE/src/answers/answers.controller.ts
  BE/src/auth/auth.controller.ts
  BE/src/main.ts
  BE/src/questions/dto/create-question.dto.ts
  BE/src/questions/dto/read-question-list.dto.ts
  BE/src/questions/dto/read-question.dto.ts
  BE/src/questions/dto/update-question.dto.ts
  BE/src/questions/questions.controller.ts
  BE/src/users/users.controller.ts
  BE/yarn.lock
Labels: FE, BE, docs

#152 질문 초안 작성 API 수정
  BE/src/questions/dto/read-question-draft.dto.ts
  BE/src/questions/questions.controller.ts
  BE/src/questions/questions.service.ts
Labels: enhancement, BE

#151 문제 상세 내용 레이아웃 관련 컴포넌트 구현(TagButton, QuestionDetailContent)
  FE/.eslintrc.cjs
  FE/src/assets/icons/arrow-back.svg
  FE/src/assets/icons/eye.svg
  FE/src/assets/icons/index.ts
  FE/src/assets/icons/kebab.svg
  FE/src/assets/icons/like.svg
  FE/src/components/QuestionDetailContent/QuestionDetailContent.styles.ts
  FE/src/components/QuestionDetailContent/QuestionDetailContent.tsx
  FE/src/components/TagButton/TagButton.styles.ts
  FE/src/components/TagButton/TagButton.tsx
  FE/src/components/index.ts
  FE/src/types/type.d.ts
Labels: new feature, FE

#149 질문 읽기 API 수정
  BE/src/questions/dto/read-question.dto.ts
  BE/src/questions/questions.service.ts
Labels: enhancement, BE

#154 질문 리스트 API 기능 확장
  BE/src/questions/dto/read-question-list-options.dto.ts
  BE/src/questions/questions.controller.ts
  BE/src/questions/questions.service.ts
Labels: enhancement, BE

#145 오늘의 질문 API
  BE/src/questions/dto/create-question.dto.ts
  BE/src/questions/questions.controller.ts
  BE/src/questions/questions.service.ts
Labels: new feature, BE

#159 dev용 dockerfile 추가
  BE/dev.dockerfile
Labels: bug

#160 dev용 dockerfile 수정
  BE/dev.dockerfile
Labels: bug

#161 dev dependency에 있는 swagger가 개발 서버에서 잘 작동하지 않는 문제
  BE/dev.dockerfile
Labels: bug

#162 HOTFIX | 질문리스트 신규 API 반영을 통한 버그 해결
  FE/src/components/QuestionList/QuestionList.tsx
Labels: bug, FE

#155 128 문제 작성 페이지 api 연동
  FE/.eslintrc.cjs
  FE/env.d.ts
  FE/package-lock.json
  FE/package.json
  FE/src/api/questionService.ts
  FE/src/components/MainNav/MainNav.tsx
  FE/src/hooks/useDidMountEffect.ts
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.style.ts
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.tsx
  FE/src/utils/network.ts
  FE/tsconfig.json
  FE/vite.config.js
Labels: review, new feature, FE

#166 165 임시글 저장 처리
  FE/src/api/questionService.ts
  FE/src/components/DocumentEditor/DocumentEditor.tsx
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.tsx
  FE/src/types/type.d.ts
Labels: review, new feature, FE

#163 질문 상세 답변 페이지 레이아웃 구현
  FE/src/App.tsx
  FE/src/components/QuestionList/QuestionList.tsx
  FE/src/components/Scroller/Scroller.tsx
  FE/src/components/index.ts
  FE/src/pages/QuestionDetailPage/QuestionDetailPage.styles.ts
  FE/src/pages/QuestionDetailPage/QuestionDetailPage.tsx
  FE/src/pages/index.ts
Labels: new feature, FE

#171 질문에 대한 답변 리스트 API
  BE/src/answers/answers.controller.ts
  BE/src/answers/answers.service.ts
Labels: new feature, BE

#175 SWAGGER curl 요청 경로 오류 수정
  BE/src/main.ts
Labels: enhancement, BE

#170 질문 초안 작성 dto 수정
  BE/src/answers/dto/adopt-answer.dto.ts
  BE/src/answers/dto/create-answer.dto.ts
  BE/src/auth/DTO/login.dto.ts
  BE/src/likes/create-likes.dto.ts
  BE/src/questions/dto/read-question-list-options.dto.ts
  BE/src/questions/dto/update-question-draft.dto.ts
  BE/src/users/dto/create-user.dto.ts
Labels: enhancement, BE

#180 답변에 질문이 링크되지 않는 문제 수정
  BE/src/answers/answers.service.ts
  BE/src/answers/dto/create-answer.dto.ts
Labels: bug, BE

#181 답변 생성 DTO의 questionId 타입 수정
  BE/src/answers/dto/create-answer.dto.ts
Labels: bug, FE, BE

#182 빌드 오류 방지를 위한 CI 워크플로
  .github/workflows/CI.yml
  BE/src/answers/answers.service.ts
Labels: CI/CD

#178 SWAGGER 설정 변경
  BE/src/main.ts
  BE/src/questions/dto/read-question-list-options.dto.ts
Labels: enhancement, bug, BE

#173 125 질문 검색 페이지 레이아웃 구현
  FE/src/App.tsx
  FE/src/components/MainHeader/MainHeader.styles.ts
  FE/src/components/MainHeader/MainHeader.tsx
  FE/src/components/Pagination/Pagination.tsx
  FE/src/components/QuestionList/QuestionList.tsx
  FE/src/components/index.ts
  FE/src/pages/QuestionSearchPage/QuestionSearchPage.style.ts
  FE/src/pages/QuestionSearchPage/QuestionSearchPage.tsx
  FE/src/pages/index.ts
Labels: review, new feature, FE

#184 질문리스트 컴포넌트 수정
  FE/src/components/Pagination/Pagination.tsx
  FE/src/components/QuestionList/QuestionList.tsx
  FE/src/pages/MainPage/MainPage.tsx
  FE/src/pages/QuestionSearchPage/QuestionSearchPage.tsx
  FE/src/types/type.d.ts
Labels: FE, refactor

#185 167 질문 검색 페이지 api 연동
  FE/src/components/Pagination/Pagination.tsx
  FE/src/components/QuestionList/QuestionList.tsx
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.tsx
  FE/src/pages/QuestionSearchPage/QuestionSearchPage.tsx
Labels: review, new feature, FE

#176 문제 상세 내용 관련 API 연동
  FE/public/images/walking-penguin.webp
  FE/src/api/index.ts
  FE/src/components/Loading/Loading.styles.ts
  FE/src/components/Loading/Loading.tsx
  FE/src/components/QuestionAnswerCard/QuestionAnswerCard.styles.ts
  FE/src/components/QuestionAnswerCard/QuestionAnswerCard.tsx
  FE/src/components/QuestionDetailContent/QuestionDetailContent.tsx
  FE/src/components/QuestionList/QuestionList.tsx
  FE/src/components/TagButton/TagButton.styles.ts
  FE/src/components/TagButton/TagButton.tsx
  FE/src/components/index.ts
  FE/src/pages/QuestionDetailPage/QuestionDetailPage.styles.ts
  FE/src/pages/QuestionDetailPage/QuestionDetailPage.tsx
  FE/src/types/type.d.ts
Labels: new feature, FE

#183 회원가입, 로그인 레이아웃 구현 외 1
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/components/QuestionProfile/QuestionProfile.tsx
  FE/src/pages/LoginPage/LoginPage.styles.ts
  FE/src/pages/LoginPage/LoginPage.tsx
  FE/src/pages/SignupPage/SignupPage.styles.ts
  FE/src/pages/SignupPage/SignupPage.tsx
  FE/src/pages/index.ts
Labels: new feature, FE
