Repository boostcampwm2023/web04-ALGOCEAN, pull requests merged in 2023-12, with the labels that each got.

#172 급상승 질문 API
  BE/prisma/schema.prisma
  BE/src/questions/questions.controller.ts
  BE/src/questions/questions.service.ts
Labels: new feature, BE

#207 회원가입 및 로그인 API 연동
  FE/src/App.tsx
  FE/src/api/auth.ts
  FE/src/components/QuestionProfile/QuestionProfile.styles.ts
  FE/src/components/QuestionProfile/QuestionProfile.tsx
  FE/src/contexts/AuthContexts.ts
  FE/src/pages/LoginPage/LoginPage.styles.ts
  FE/src/pages/LoginPage/LoginPage.tsx
  FE/src/pages/SignupPage/SignupPage.styles.ts
  FE/src/pages/SignupPage/SignupPage.tsx
  FE/src/types/type.d.ts
Labels: new feature, FE

#208 HOTFIX | 검색페이지가 사라진 버그 수정
  FE/src/App.tsx
Labels: FE

#197 196 좋아요 기능이 작동하지 않음
  BE/src/app.module.ts
  BE/src/main.ts
Labels: bug, BE

#209 본인이 작성한 질문 답변에 대한 리스트를 받는 API
  BE/src/answers/answers.service.ts
  BE/src/questions/questions.service.ts
  BE/src/users/users.controller.ts
  BE/src/users/users.module.ts
Labels: enhancement, BE

#211 refresh API jwt 응답 방식 수정
  BE/src/auth/auth.controller.ts
Labels: enhancement, BE

#210 130 프로필 인포 컴포넌트 레이아웃 구현
  FE/public/images/Programmer.png
  FE/src/components/ProfileInfo/ProfileInfo.styles.tsx
  FE/src/components/ProfileInfo/ProfileInfo.tsx
  FE/src/components/index.ts
Labels: review, new feature, FE

#213 프로필 API
  BE/src/answers/answers.service.ts
  BE/src/auth/auth.service.ts
  BE/src/questions/questions.service.ts
  BE/src/users/users.controller.ts
  BE/src/users/users.service.ts
Labels: enhancement, BE

#220 refreshToken 파싱 오류 수정
  BE/src/auth/auth.controller.ts
  BE/src/auth/strategies/github.strategy.ts
Labels: bug, BE

#215 137 프로필 자기가 올린 질문리스트 레이아웃 구현
  FE/src/components/ProfileQuestionList/ProfileQuestionList.styles.ts
  FE/src/components/ProfileQuestionList/ProfileQuestionList.tsx
  FE/src/components/index.ts
Labels: review, new feature, FE

#218 123 프로필 페이지 api 연동
  FE/src/api/profile.ts
  FE/src/components/ProfileAnswerList/ProfileAnswerList.tsx
  FE/src/components/ProfileInfo/ProfileInfo.tsx
  FE/src/components/ProfileQuestionList/ProfileQuestionList.tsx
  FE/src/pages/ProfilePage/ProfilePage.tsx
  FE/src/types/type.d.ts
Labels: new feature, FE

#214 사용자 인증 여부에 따른 접근 가능 페이지 및 기능 구분
  BE/src/main.ts
  FE/src/App.tsx
  FE/src/api/auth.ts
  FE/src/api/index.ts
  FE/src/api/questionService.ts
  FE/src/components/DocumentEditor/DocumentEditor.tsx
  FE/src/components/MainNav/MainNav.tsx
  FE/src/components/QuestionAnswerRequestCard/QuestionAnswerRequestCard.tsx
  FE/src/components/QuestionProfile/QuestionProfile.styles.ts
  FE/src/components/QuestionProfile/QuestionProfile.tsx
  FE/src/contexts/AuthContexts.ts
  FE/src/contexts/AuthContexts.tsx
  FE/src/pages/LoginPage/LoginPage.tsx
  FE/src/pages/MainPage/MainPage.tsx
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.tsx
  FE/src/pages/QuestionDetailPage/QuestionDetailPage.tsx
  FE/src/pages/SignupPage/SignupPage.tsx
  FE/src/router/index.tsx
  FE/src/types/type.d.ts
Labels: new feature, FE

#222 COOKIE 설정 추가
  FE/src/utils/network.ts
Labels: bug, FE

#226 E2E 테스트
  BE/package.json
  BE/test.dockerfile.yml
  BE/test/app.e2e-spec.ts
  BE/yarn.lock
Labels: BE

#234 223 react query 적용
  FE/package-lock.json
  FE/package.json
  FE/src/pages/MainPage/MainPage.tsx
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.tsx
  FE/src/pages/QuestionSearchPage/QuestionSearchPage.tsx
  FE/src/router/index.tsx
Labels: enhancement, new feature, FE

#232 hotfix | 상세 질문 페이지 무한로딩
  FE/src/api/questionService.ts
  FE/src/components/QuestionAnswerFormCard/QuestionAnswerFormCard.tsx
  FE/src/pages/NotFoundPage/NotFoundPage.styles.ts
  FE/src/pages/NotFoundPage/NotFoundPage.tsx
  FE/src/pages/QuestionDetailPage/QuestionDetailPage.tsx
  FE/src/pages/index.ts
  FE/src/router/index.tsx
  FE/src/styles/reset.css
  FE/src/utils/network.ts
Labels: bug, new feature, FE

#240 오늘의 질문, 랜덤 질문 API 수정
  BE/src/questions/questions.controller.ts
  BE/src/questions/questions.service.ts
Labels: enhancement, BE

#242 오늘의 질문, 랜덤 질문, 급상승 질문 API 수정
  BE/src/questions/questions.service.ts
Labels: enhancement, BE

#250 249 질문 등록 페이지 피드백 반영
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.tsx
Labels: enhancement, FE, refactor

#248 247 기능 3대장이 작동하지 않는 버그
  BE/src/questions/questions.controller.ts
  BE/src/questions/questions.service.ts
Labels: bug, BE

#253 206 k8s 배포
  BE/.prettierrc
  BE/dockerfile
  BE/package.json
  BE/prisma/schema.prisma
  BE/src/main.ts
  FE/dockerfile
  FE/nginx.conf
Labels: enhancement, CI/CD

#255 user API 버그 수정
  BE/src/auth/strategies/jwt.strategy.ts
  BE/src/users/users.controller.ts
Labels: bug, BE

#252 251 sweetalert2 적용
  FE/package-lock.json
  FE/package.json
  FE/src/components/MainHeader/MainHeader.tsx
  FE/src/components/MainNav/MainNav.tsx
  FE/src/components/QuestionAnswerFormCard/QuestionAnswerFormCard.tsx
  FE/src/components/QuestionProfile/QuestionProfile.tsx
  FE/src/pages/LoginPage/LoginPage.tsx
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.tsx
  FE/src/pages/QuestionDetailPage/QuestionDetailPage.tsx
  FE/src/pages/SignupPage/SignupPage.tsx
  FE/src/styles/reset.css
Labels: enhancement, new feature, FE

#263 CWV - Accessibility 개선
  FE/src/assets/icons/eye.svg
  FE/src/assets/icons/index.ts
  FE/src/assets/icons/write.svg
  FE/src/components/MainNav/MainNav.tsx
  FE/src/components/Pagination/Pagination.styles.ts
  FE/src/components/Pagination/Pagination.tsx
  FE/src/components/QuestionList/QuestionList.styles.ts
  FE/src/components/QuestionList/QuestionList.tsx
  FE/src/components/UniqueQuestions/UniqueQuestions.styles.ts
  FE/src/styles/theme.ts
Labels: enhancement, FE

#267 FE에 dist 디렉토리 생성
  .github/workflows/CI.yml
Labels: bug, CI/CD

#269 SWAGGER 버그 수정
  BE/src/main.ts
Labels: bug, BE

#271 랭킹 API
  BE/src/users/users.controller.ts
  BE/src/users/users.service.ts
Labels: new feature, BE

#272 HOTFIX | Github callback url 수정
  BE/src/auth/strategies/github.strategy.ts
Labels: bug, FE

#266 264 검색 엔진 최적화 (SEO)
  FE/index.html
  FE/package-lock.json
  FE/package.json
  FE/public/robots.txt
  FE/public/sitemap.xml
  FE/src/components/DocumentEditor/DocumentEditor.tsx
  FE/src/main.tsx
  FE/src/metas/metas.tsx
  FE/src/pages/LoginPage/LoginPage.tsx
  FE/src/pages/MainPage/MainPage.tsx
  FE/src/pages/NotFoundPage/NotFoundPage.tsx
  FE/src/pages/ProfilePage/ProfilePage.tsx
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.tsx
  FE/src/pages/QuestionDetailPage/QuestionDetailPage.tsx
  FE/src/pages/QuestionSearchPage/QuestionSearchPage.tsx
  FE/src/pages/SignupPage/SignupPage.tsx
  FE/src/router/index.tsx
Labels: enhancement, new feature, FE

#274 랭킹 게시판 구현
  FE/src/api/index.ts
  FE/src/api/ranking.ts
  FE/src/components/MainNav/MainNav.styles.ts
  FE/src/components/MainNav/MainNav.tsx
  FE/src/components/RankingItem/RankingItem.styles.ts
  FE/src/components/RankingItem/RankingItem.tsx
  FE/src/components/index.ts
  FE/src/pages/RankingPage/RankingPage.style.ts
  FE/src/pages/RankingPage/RankingPage.tsx
  FE/src/pages/index.ts
  FE/src/router/index.tsx
  FE/src/types/type.d.ts
Labels: new feature, FE

#280 랭킹 API 응답 수정
  BE/src/users/users.service.ts
Labels: enhancement, BE

#261 README.md 초안 작성
  README.md
Labels: docs

#281 깃허브 소셜 로그인 구현
  FE/src/api/auth.ts
  FE/src/api/index.ts
  FE/src/pages/GithubCallbackPage/GithubCallbackpage.tsx
  FE/src/pages/LoginPage/LoginPage.styles.ts
  FE/src/pages/LoginPage/LoginPage.tsx
  FE/src/pages/index.ts
  FE/src/router/index.tsx
Labels: new feature, FE, BE

#285 본인 프로필 조회 API 수정
  BE/src/users/users.controller.ts
  BE/src/users/users.service.ts
Labels: enhancement, BE

#283 한글 검색 키워드 추가
  FE/src/metas/metas.tsx
Labels: enhancement, FE

#278 랭킹 페이지 본인 랭킹 구현
  FE/src/App.tsx
  FE/src/api/auth.ts
  FE/src/api/index.ts
  FE/src/api/ranking.ts
  FE/src/components/RankingItem/RankingItem.styles.ts
  FE/src/components/RankingItem/RankingItem.tsx
  FE/src/pages/GithubCallbackPage/GithubCallbackpage.tsx
  FE/src/pages/LoginPage/LoginPage.tsx
  FE/src/pages/RankingPage/RankingPage.style.ts
  FE/src/pages/RankingPage/RankingPage.tsx
  FE/src/types/type.d.ts
Labels: new feature, FE

#286 243 프로필 페이지 api 수정
  BE/src/users/users.controller.ts
  FE/src/api/profile.ts
  FE/src/components/MainNav/MainNav.tsx
  FE/src/components/ProfileInfo/ProfileInfo.tsx
  FE/src/pages/ProfilePage/ProfilePage.tsx
  FE/src/router/index.tsx
Labels: FE, refactor

#287 276 임시 저장 불러오기 기능 구현
  FE/package-lock.json
  FE/package.json
  FE/src/api/index.ts
  FE/src/api/questionService.ts
  FE/src/components/DocumentEditor/DocumentEditor.tsx
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.style.ts
  FE/src/pages/QuestionCreationPage/QuestionCreationPage.tsx
  FE/src/types/type.d.ts
Labels: enhancement, new feature, FE

#289 288-프로필-페이지-rank-반영
  FE/src/components/ProfileInfo/ProfileInfo.tsx
  FE/src/pages/ProfilePage/ProfilePage.tsx
Labels: FE, refactor

#291 로그인 도중 에러가 날 시 로그인을 취소하는 로직 추가
  BE/src/users/users.controller.ts
  FE/src/api/auth.ts
  FE/src/pages/LoginPage/LoginPage.tsx
Labels: bug, FE

#293 feat: HTML 파일 추가
  FE/public/naver130d9870c2d27e8ec63f94ecbc3b6bb3.html
Labels: FE

#297 /answers/:questionId API 응답 수정
  BE/src/answers/answers.controller.ts
Labels: enhancement, BE

#265 인증 관련 코드 삽입
  BE/src/answers/answers.controller.ts
  BE/src/answers/answers.service.ts
  BE/src/auth/auth.controller.ts
  BE/src/likes/likes.controller.ts
  BE/src/main.ts
  BE/src/questions/questions.controller.ts
  BE/src/users/users.controller.ts
Labels: new feature, BE

#300 feat: sitemap 수정
  FE/index.html
  FE/public/sitemap.xml
  FE/src/metas/metas.tsx
  FE/src/router/index.tsx
Labels: FE

#302 sse module 의존성 오류
  BE/src/users/users.module.ts
Labels: bug, BE

#307 sse test용 코드
  BE/src/polling/polling.controller.ts
  BE/src/polling/polling.service.ts
  sse/.yarn/install-state.gz
  sse/src/alarm/alarm.controller.ts
  sse/src/alarm/alarm.service.ts
Labels: BE

#308 Readme 수정
  README.md
Labels: docs

#311 fix: 프로필 페이지 나의 질문 수정
  FE/src/components/ProfileQuestionList/ProfileQuestionList.tsx
  FE/src/types/type.d.ts
Labels: bug, FE

#310 프로필 나의 답변 버그 수정
  BE/src/answers/answers.service.ts
Labels: bug, BE
